### PR TITLE
Simplify detect Alpine Linux

### LINKED ISSUE #155: Fedora is assumed as Alpine
## Describe the bug
When try `ducere serve`, outputs `/path/to/home/.asdf/installs/nim/1.4.8/nimble/pkgs/basolato-0.9.1/basolato/core/utils.nim(36, 27) Error: cannot open file: /lib/apk/db/installed`

`ducere serve`を実行したときに、`/path/to/home/.asdf/installs/nim/1.4.8/nimble/pkgs/basolato-0.9.1/basolato/core/utils.nim(36, 27) Error: cannot open file: /lib/apk/db/installed`が表示される

## Steps to reproduce
In Fedora 34, type `ducere serve`

Fedora 34で、`ducere serve`を実行する

## Expected behavior
`ldconfig -p | grep libsass` would executed instead

`ldconfig -p | grep libsass`が代わりに実行される

## Screenshots
image

## Additional context
`nim` -> 1.4.8
`basolato` -> 0.9.1

`cat /etc/os-release` results:

```
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

^ As you can see, `ID` specifies it's `fedora` (from reading source code)

^ `ID`が`fedora`になってることがわかると思います。

### PR DESCRIPTION
**Pull request by kubo39**
This could potentially fixes #155, though I'm not sure.

### CODE REVIEW

**Review by itsumura-h — APPROVED** [review]
LGTM

**Comment by kubo39** [comment]
Sorry, CI failure is due to lack of my concern so I'll rebase.

**Comment by itsumura-h** [comment]
@kubo39 
CI error seems to be caused by  stdlib `distros`.

```nim
proc isExistsLibsass*():bool =
  ## used in /view
  when defined(macosx):
    const query = "ldconfig -p | grep libsass"
    const res = gorgeEx(query)
    return res.exitCode == 0 and res.output.len > 0
  elif defined(linux) or defined(bsd):
    when detectOS(Alpine):
```

```sh
/nim/lib/pure/distros.nim(148, 52) Error: cannot evaluate at compile time: unameRes
```

**Comment by kubo39** [comment]
Hmm, CI has still broken.

```console
+ cd /root/project/tests/server
+ nim c main
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: used config file '/nim/config/config.nims' [Conf]
Hint: used config file '/root/project/tests/config.nims' [Conf]
......................................................................................
/root/project/src/basolato/core/utils.nim(21, 6) Error: 'isExistsLibsass' can have side effects
1
Error: Process completed with exit code 1.
```

**Comment by itsumura-h** [comment]
@kubo39 
You can relace

```nim
func isExistsLibsass*():bool =
```
to:
```nim
proc isExistsLibsass*():bool =
```

**Comment by kubo39** [comment]
I gotta, `when isExistsLibsass():` casues this failure.
Closing now.

**Pull request closed without merging**
